---
# all non secret vars
zfs: {
  poolName: dataPool,
  DISK1: '/dev/disk/by-id/ata-VBOX_HARDDISK_VBdb921551-0235d4da',
  DISK2: '/dev/disk/by-id/ata-VBOX_HARDDISK_VB63d0dcbf-e8993416',
  CACHEDISK: '/dev/disk/by-id/ata-VBOX_HARDDISK_VB119a87ff-73029b84',
}

usergroups:
  - family
  - admins

users:
  - {name: 'mainuser', groups: 'family, admins', smbpasswd: 'mainuser'}
  - {name: 'otheruser', groups: 'family', smbpasswd: 'otheruser'}
  - {name: 'thirduser', groups: 'family', smbpasswd: 'thirduser'}
  - {name: 'userNotInGroups', groups: '', smbpasswd: 'userNotInGroups'}

adminuser: mainuser # should be an existing one from above

shared_folders:
  - {name: 'Images', path: '/{{zfs.poolName}}/media/images'}
  - {name: 'Music', path: '/{{zfs.poolName}}/media/music'}
  - {name: 'Shared folder', path: '/{{zfs.poolName}}/personal/all'}
  - {name: 'Shared Backup Folder', path: '/{{zfs.poolName}}/backup/all'}

shared_folders_group: family

docker: {
  external_network: net_proxy,
  data_dir: '/{{zfs.poolName}}/docker/data',
  # data for docker env
  PUID: '1000',
  PGID: '115'
}
