zfs:
  poolName: dataPool
  disks:
    - /dev/disk/by-id/ata-VBOX_HARDDISK_VB1e8d1f50-ba9244f7
    - /dev/disk/by-id/ata-VBOX_HARDDISK_VB31894c10-b40e4ca9
  cacheDisk:
    - /dev/disk/by-id/ata-VBOX_HARDDISK_VB53c5abdb-561c51fe

user_groups:
  - family
  - admins

users:
  - name: mainuser
    groups:
      - family
      - admins
    # Replace smbpasswd with a secure password storage mechanism
    # smbpasswd: 'mainuser'
  - name: otheruser
    groups:
      - family
    # Replace smbpasswd with a secure password storage mechanism
    # smbpasswd: 'otheruser'
  - name: thirduser
    groups:
      - family
    # Replace smbpasswd with a secure password storage mechanism
    # smbpasswd: 'thirduser'
  - name: userNotInGroups
    # Replace smbpasswd with a secure password storage mechanism
    # smbpasswd: 'userNotInGroups'

admin_user: mainuser

shared_folders:
  - name: images
    path: /{{ zfs.poolName }}/media/images
  - name: music
    path: /{{ zfs.poolName }}/media/music
  - name: shared_folder
    path: /{{ zfs.poolName }}/personal/all
  - name: shared_backup_folder
    path: /{{ zfs.poolName }}/backup/all

shared_folders_group: family

docker:
  external_network: net_proxy
  data_dir: /{{ zfs.poolName }}/docker/data
  media_storag: /media/storage
  hostname: udms
  puid: 1000
  pgid: 115
