zfs:
  {
    poolName: dataPool,
    DISK1: "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VB61655acf-9bfaf9c4",
    DISK2: "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBbfc11fb4-dc8b053e",
    CACHEDISK: "/dev/disk/by-id/scsi-SATA_VBOX_HARDDISK_VBc08b0182-09be4c50",
  }

user_groups:
  - family
  - admins

users:
  - { name: "habnai", groups: "family, admins", smbpasswd: "mainuser" }
  - { name: "otheruser", groups: "family", smbpasswd: "otheruser" }
  - { name: "thirduser", groups: "family", smbpasswd: "thirduser" }
  - { name: "userNotInGroups", groups: "", smbpasswd: "userNotInGroups" }


adminuser: habnai

shared_folders:
  - { name: "Images", path: "/{{zfs.poolName}}/media/images" }
  - { name: "files", path: "/{{zfs.poolName}}/personal/files" }
  - { name: "Shared folder", path: "/{{zfs.poolName}}/personal/all" }
  - { name: "Shared Backup Folder", path: "/{{zfs.poolName}}/backup/all" }


shared_folders_group: family

docker:
  data_dir: /{{ zfs.poolName }}/docker/data
  media_storage: /media/storage
  PUID: 1000
  PGID: 115
