---
- name: Setup docker .env file
  template:
    src: templates/dockerEnv.env
    dest: "../.env"

- name: Update DNF cache
  dnf:
    name: '*'
    state: latest
  become: yes

- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest
  become: yes

- name: Install required dependencies
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - dnf-plugins-core
    - yum-utils
- name: Add Docker GPG key
  command: "{{ item }}"
  loop:
    - rpm --import https://download.docker.com/linux/centos/gpg
- name: Add Docker repository
  command: "{{ item }}"
  loop:
    - dnf config-manager --add-repo=https://download.docker.com/linux/centos/9/$basearch/stable

- name: Install Docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  notify: Start and enable docker

- name: Ensure docker group exists
  group:
    name: docker
    state: present
- name: 'Add user {{ adminuser }} to docker group'
  user:
    name: '{{ adminuser }}'
    groups: docker
    append: 'yes'

- name: Create folder for docker data
  file:
    path: "{{docker.data_dir}}"
    state: directory

- name: Create folder for custom
  file:
    path: "{{docker.data_dir}}/custom"
    state: directory

- name: Create folder for logs
  file:
    path: "{{docker.data_dir}}/logs"
    state: directory

- name: Create folder for scripts
  file:
    path: "{{docker.data_dir}}/scripts"
    state: directory

- name: Create folder for secrets
  file:
    path: "{{docker.data_dir}}/secrets"
    state: directory

- name: Create folder for shared
  file:
    path: "{{docker.data_dir}}/shared"
    state: directory


