---
- name: Install generic needed packages
  ansible.builtin.dnf:
    name:
      - samba
      - samba-common
      - samba-client
    state: latest
  become: true # This should be a boolean (yes or no)

- name: Start and enable the smb service
  ansible.builtin.systemd:
    name: smb
    enabled: yes
    state: started
  become: true # Correct usage

- name: Create/update samba users
  include_tasks: smbusers.yml
  loop: "{{ users }}"

- name: Configure samba shares
  ansible.builtin.template:
    src: homeserver_smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
  become: true # Correct usage
  notify:
    - Restart smbd

- name: Restart smbd service after share configuration
  ansible.builtin.systemd:
    name: smb
    state: restarted
  become: true # Correct usage

- name: Add Samba service to firewalld
  firewalld:
    service: samba
    zone: public
    permanent: yes
    state: enabled
    immediate: yes

- name: Reload firewalld to apply changes
  systemd:
    name: firewalld
    state: reloaded

- name: Restart smbd
  ansible.builtin.systemd:
    name: smb
    state: restarted
  become: true # Correct usage
