---
- name: Setup docker .env file
  template:
    src: templates/dockerEnv.env
    dest: "../.env"

- name: Update apt repositories
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: Download Docker GPG key
  shell: "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg"

- name: Add Docker repository
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ ansible_dpkg_architecture }} signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable"
    notify: Update apt repositories

handlers:
- name: Update apt repositories
  apt:
    update_cache: yes

- name: Install Docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  notify: Start and enable docker

- name: Ensure docker group exists
  group:
    name: docker
    state: present
- name: 'Add user {{ adminuser }} to docker group'
  user:
    name: '{{ adminuser }}'
    groups: docker
    append: 'yes'

- name: Create folder for docker data
  file:
    path: "{{docker.data_dir}}"
    state: directory

- name: Create folder for custom
  file:
    path: "{{docker.data_dir}}/custom"
    state: directory

- name: Create folder for logs
  file:
    path: "{{docker.data_dir}}/logs"
    state: directory

- name: Create folder for scripts
  file:
    path: "{{docker.data_dir}}/scripts"
    state: directory

- name: Create folder for secrets
  file:
    path: "{{docker.data_dir}}/secrets"
    state: directory

- name: Create folder for shared
  file:
    path: "{{docker.data_dir}}/shared"
    state: directory


