---
- name: Setup docker .env file
  ansible.builtin.template:
    src: templates/dockerEnv.env
    dest: "../.env"
    owner: root
    group: root
    mode: "0600"
  become: true

- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - dnf-plugins-core
    - yum-utils
    - git
    - ca-certificates
    - wget
    - gnupg2
    - curl
    - acl
  become: true

- name: Add Docker repository
  ansible.builtin.command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  become: true

- name: Install Docker
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  become: true

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user {{ adminuser }} to docker group
  ansible.builtin.user:
    name: "{{ adminuser }}"
    groups: docker
    append: yes
  become: true

- name: Create folder for docker data
  ansible.builtin.file:
    path: "{{ docker.data_dir }}"
    state: directory
  become: true

- name: Create folder for logs
  ansible.builtin.file:
    path: "{{ docker.data_dir }}/logs"
    state: directory
  become: true

- name: Create folder for scripts
  ansible.builtin.file:
    path: "{{ docker.data_dir }}/scripts"
    state: directory
  become: true

- name: Create folder for secrets
  ansible.builtin.file:
    path: "{{ docker.data_dir }}/secrets"
    state: directory
    owner: root
    group: root
    mode: "0600"
  become: true

- name: Create folder for shared
  ansible.builtin.file:
    path: "{{ docker.data_dir }}/shared"
    state: directory
  become: true

- name: Ensure docker data has 775 permissions
  file:
    path: "{{ docker.data_dir }}"
    state: directory
    mode: "0775"
