--
- name: Setup docker .env file
  template:
    src: templates/dockerEnv.env
    dest: "../.env"
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - dnf-plugins-core
    - yum-utils
    - git
    - apt-transport-https
    - ca-certificates
    - wget
    - software-properties-common
    - gnupg2
    - curl
  when: ansible_distribution == 'Alma Linux'

- name: Add Docker repository
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == 'Alma Linux'

- name: Install Docker
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when: ansible_distribution == 'Alma Linux'

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  when: ansible_distribution == 'Alma Linux'

- name: Ensure docker group exists
  group:
    name: docker
    state: present
- name: 'Add user {{ adminuser }} to docker group'
  user:
    name: '{{ adminuser }}'
    groups: docker
    append: 'yes'

- name: Create folder for docker data
  file:
    path: "{{docker.data_dir}}"
    state: directory

- name: Create folder for custom
  file:
    path: "{{docker.data_dir}}/custom"
    state: directory

- name: Create folder for logs
  file:
    path: "{{docker.data_dir}}/logs"
    state: directory

- name: Create folder for scripts
  file:
    path: "{{docker.data_dir}}/scripts"
    state: directory

- name: Create folder for secrets
  file:
    path: "{{docker.data_dir}}/secrets"
    state: directory

- name: Create folder for shared
  file:
    path: "{{docker.data_dir}}/shared"
    state: directory


