---
- name: Setup docker .env file
  template:
    src: templates/dockerEnv.env
    dest: "../.env"
- name: Update the apt package index
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes
- name: Install packages for apt add repository over HTTPS
  become: yes
  apt:
    name: "{{ packagesdep }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  vars:
    packagesdep:
    - git
    - apt-transport-https
    - ca-certificates
    - wget
    - software-properties-common
    - gnupg2
    - curl
- name: Add Apt signing key from official docker repo
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: add docker official repository for Debian
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
    state: present
- name: Index new repo into the cache
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  notify: Start and enable docker

- name: Ensure docker group exists
  group:
    name: docker
    state: present
- name: 'Add user {{ adminuser }} to docker group'
  user:
    name: '{{ adminuser }}'
    groups: docker
    append: 'yes'

- name: Create folder for docker data
  file:
    path: "{{docker.data_dir}}"
    state: directory

- name: Create folder for custom
  file:
    path: "{{docker.data_dir}}/custom"
    state: directory

- name: Create folder for logs
  file:
    path: "{{docker.data_dir}}/logs"
    state: directory

- name: Create folder for scripts
  file:
    path: "{{docker.data_dir}}/scripts"
    state: directory

- name: Create folder for secrets
  file:
    path: "{{docker.data_dir}}/secrets"
    state: directory

- name: Create folder for shared
  file:
    path: "{{docker.data_dir}}/shared"
    state: directory


