---
- name: Install generic needed packages
  dnf:
    name:
    - samba
    - samba-common
    - samba-client
    state: latest

- name: Start and enable the smb service
  systemd:
    name: smb
    enabled: yes
    state: started

- name: Create/update samba users
  include_tasks: "smbusers.yml"
  loop: "{{users}}"

- name: Configuring samba shares
  template:
    src: homeserver_smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
- name: Restart smb service after share configuration
  systemd:
    name: smb
    state: restarted
