---
- name: Ensure user groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ usergroups }}"

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    append: yes
    update_password: on_create
  loop: "{{ users }}"

- name: Create personal folders for users
  ansible.builtin.file:
    path: "/{{ zfs.poolName }}/personal/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ users }}"

- name: Create backup folder for users
  ansible.builtin.file:
    path: "/{{ zfs.poolName }}/backup/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0700"
  loop: "{{ users }}"

- name: Create shared folders
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    group: "{{ shared_folders_group }}"
    mode: "2771" # equivalent to u=rwx,g=rwx,o=rx,g+s
  loop: "{{ shared_folders }}"
