########################### NETWORKS
# You may customize the network subnets (192.168.x.0/24) below as you please.
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.91.0/24

########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/basic_auth_credentials
  guac_db_name:
    file: $DOCKERDIR/secrets/guac_db_name
  guac_mysql_user:
    file: $DOCKERDIR/secrets/guac_mysql_user
  guac_mysql_password:
    file: $DOCKERDIR/secrets/guac_mysql_password

include:
  ########################### SERVICES
  # PREFIX hs = Home Server
  # HOSTNAME=hs - defined in .env

  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/dockge.yml
  # SECURITY
  - compose/$HOSTNAME/crowdsec.yml
  # FRONTEND
  - compose/$HOSTNAME/autoindex.yml
  - compose/$HOSTNAME/homepage.yml
  - compose/$HOSTNAME/phpmyadmin.yml
  - compose/$HOSTNAME/sitespeed.yml
  - compose/$HOSTNAME/whoami.yml
  # DOWNLOADERS
  # - compose/$HOSTNAME/jdownloader.yml
  - compose/$HOSTNAME/qbittorrent.yml
  - compose/$HOSTNAME/sabnzbd.yml
  # PVRS
  - compose/$HOSTNAME/sonarr.yml
  - compose/$HOSTNAME/radarr.yml
  # - compose/$HOSTNAME/lidarr.yml
  # COMPLEMENTARY APPS
  - compose/$HOSTNAME/prowlarr.yml
  - compose/$HOSTNAME/notifiarr.yml
  # - compose/$HOSTNAME/bazarr.yml
  # - compose/$HOSTNAME/picard.yml
  # MONITORING
  - compose/$HOSTNAME/grafana.yml
  - compose/$HOSTNAME/uptime-kuma.yml
  - compose/$HOSTNAME/dozzle.yml
  - compose/$HOSTNAME/scrutiny.yml
  # - compose/$HOSTNAME/radarr-exporter.yml
  # - compose/$HOSTNAME/sonarr-exporter.yml
  # - compose/$HOSTNAME/lidarr-exporter.yml
  # - compose/$HOSTNAME/prowlarr-exporter.yml
  # - compose/$HOSTNAME/sabnzbd-exporter.yml
  - compose/$HOSTNAME/node-exporter.yml
  # ADMIN
  - compose/$HOSTNAME/guacamole.yml
  # - compose/$HOSTNAME/kasm.yml
  - compose/$HOSTNAME/it-tools.yml
  # UTILITIES
  - compose/$HOSTNAME/firefox.yml
  - compose/$HOSTNAME/firefly.yml
  # FILE MANAGEMENT
  - compose/$HOSTNAME/vscode.yml
  - compose/$HOSTNAME/makemkv.yml
  - compose/$HOSTNAME/mkvtoolnix.yml
  # NETWORK
  - compose/$HOSTNAME/gluetun.yml
  # MAINTENANCE
  - compose/$HOSTNAME/docker-gc.yml
  - compose/$HOSTNAME/deunhealth.yml
